/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 14-3月-2020 11:01:47 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Vo` CASCADE
;

/* Create Tables */

CREATE TABLE `Vo`
(
	`Id` INT NULL,
	`Name` VARCHAR(50) NULL,
	`VoID` INT NOT NULL,
	CONSTRAINT `PK_Vo` PRIMARY KEY (`VoID` ASC)
)

;

SET FOREIGN_KEY_CHECKS=1
; 
